nebs/main/urls.py
from django.urls import path
from . import views
from django.urls import include, path

urlpatterns = [
   path("", views.index, name = "index"),
   path("display/<str:cat>/", views.display, name = "display"),
   path("search/", views.search, name = "search"),
   path("booking/", views.booking, name = "booking"),
   path("offers/", views.offers, name = "offers"),
   #path("<str:name>", views.greet, name = "greet"),
]

nebs/nebs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('shoppingcart.urls')),
    path('', include('main.urls'))
]

nebs/shoppingcart/urls.py
from django.urls import path
from . import views

app_name = "shoppingcart"

urlpatterns = [
   path("cart/", views.index, name = "index"),
   path("confirmation/", views.confirm, name="confirm")
]

nebs/main/models.py
from django.db import models


# Create your models here.

#How a product will look like
class Item (models.Model):
    CATEGORY = (
        ('Cake', 'Cake'),
        ('Bread', 'Bread'),
        ('Pastry', 'Pastry'),
        ('Cookies', 'Cookies'),
        ('Moroccan', 'Moroccan')
    )
    picture = models.ImageField(upload_to = 'main/static/item-pictures')
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    description = models.CharField(max_length = 250)
    category = models.CharField(
        max_length= 30,
        choices = CATEGORY
    )
    sold_qty = models.IntegerField()
    available_qty = models.IntegerField()
    #quantity = models.IntegerField()

    def __str__(self):
        return self.category+ ': ' + self.name


#How a booking will look like
class Booking (models.Model):
    #Add status
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    day = models.CharField(max_length=100)
    time = models.CharField(max_length=100)
    description = models.CharField(max_length = 250)
    def __str__(self):
        return self.name+ ': ' + self.day + " " + self.time

nebs/shoppingcart/models.py
from __future__ import unicode_literals
from django.db import models
from main.models import Item

# Create your models here.

class client (models.Model):
    FirstName = models.CharField(max_length=120)
    LastName = models.CharField(max_length=120)
    Number = models.IntegerField()
    Address = models.CharField(max_length=500)

    def __str__(self):
        return self.FirstName + ' ' + self.LastName
        
class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)
    OrderNumber = models.CharField(max_length = 2000,null=True,blank=True)
    is_ordered = models.BooleanField(default=False)
    subtotal = models.FloatField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"
    def cal_subtotal(self):
        return self.quantity*self.item.price

class Order (models.Model):
    STATUS = (('Pending', 'Pending'),
              ('Canceled', 'Canceled'),
              ('Sold', 'Sold')
    )
    client = models.ForeignKey(client, on_delete=models.CASCADE, null=True)    
    is_ordered = models.BooleanField(default=False)
    products = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)
    OrderNumber = models.CharField(max_length = 2000,null=True,blank=True)
    STATUS = models.CharField(max_length=50, default='Pending', choices=STATUS)
    def __str__(self):
        return '{0} - {1}'.format(self.OrderNumber, self.date_ordered)

    def get_cart_items(self):
        return self.products.all()
    
    def get_cart_total(self):
        return float(sum([item.cal_subtotal() for item in self.products.all()]))

class transaction (models.Model):
    date=models.DateTimeField(auto_now=True)
    revenues=models.FloatField(default=1,blank=True)
    Orders=models.ManyToManyField(Order)
    best_selling=[]
    def get_total_revenues(self):
        Total=0
        for element in self.Orders.all():
            if(element.date_ordered==date and STATUS=='Sold'):
                for qnt in element.products.all():
                   sum+=qnt.cal_subtotal
        return Total
class best_seller(models.Model):
    product=models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    date=models.DateTimeField(auto_now=True)

nebs/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Item, Booking
from django.contrib import messages
from django.core import serializers
from json import dumps 
import json



from .models import Item
from shoppingcart.models import best_seller
import datetime
# Create your views here.
def index(request):
    now=datetime.datetime.now()
    best_selling=[]
    for obj in best_seller.objects.all():
        if(now.month==obj.date.month and now.year==obj.date.year):
             best_selling.append(obj.product)
    if(not best_selling or now.day==1):
        best_selling=Item.objects.all().order_by('-sold_qty')[:8]
        for itm in best_selling:
            j=best_seller(product=itm , date=now)
            j.save()
    return render(request, "main/index.html",{'list':best_selling})
    

def display(request, cat):  
    #Get all Items from DB and Filter it based on category
    cate = cat
    all_items = Item.objects.filter(category = cat)
    return render(request, "main/display.html", {'Items' : all_items, "Cat" : cate})
  
def search(request):
    query = request.GET['query']
    all_items = Item.objects.filter(name__icontains = query)
    params = {'Items' : all_items}
    return render(request, "main/display.html", params)

def booking(request):
    if request.method == 'POST':
        name_value = request.POST['name']
        email_value = request.POST['email']
        phone_value = request.POST['phone']
        time_value = request.POST['time']
        day_value = request.POST['day']
        description_value = request.POST['description']
        if Booking.objects.filter(day = day_value, time = time_value).exists() == False:
            b = Booking.objects.create(name = name_value, email = email_value, phone = phone_value, day = day_value, time = time_value, description = description_value)
        else:
            messages.error(request,'The time slot selected is already taken')
    #Serializing Booking
    book = json.loads(serializers.serialize('json', Booking.objects.all(), fields=('day','time')))
    return render(request, "main/booking.html", {'data': json.dumps(book)})


def offers(request):
    return HttpResponse("Offers Page")

def greet(request, name):
    return HttpResponse(f"Hello, {name}!")

nebs/shoppingcart/views.py
from django.shortcuts import render, get_object_or_404
from django import forms
from main.models import Item
from shoppingcart.models import OrderItem, Order, client
from datetime import datetime

# Create your views here.

def confirm (request):
    if not request.session.session_key:
        request.session.save()
    if not request.session.session_key:
        request.session.save()

    order_qs = Order.objects.filter(OrderNumber=request.session.session_key+"1", is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]   
        if request.method=="POST":
            FirstName = request.POST['fname']
            LastName = request.POST['lname']
            Number = request.POST['number']
            Address = request.POST['address']
            Total = request.POST.get('ttl', False)
        
            client2 = client.objects.create(FirstName = FirstName, LastName = LastName, Number = Number, Address=Address)
            order.client = client2
            order.is_ordered = True
            order.save()

            x=0
            
            for i in order.products.all():
                x += (i.item.price)*(i.quantity)

            if(Address == " "):
                order.delivery = False
                order.total = x
            else:
                x = float(Total) + 15.0 
                order.delivery = True
                order.total = x
            
            order.save()

            now = datetime.now()
            now1 = now.strftime("%m/%d/%Y, %H:%M:%S")

            order.OrderNumber = now1 + request.session.session_key+"1"
            order.save()

            for i in order.products.all():
                i. OrderNumber = request.session.session_key+ "1" + now1,
                i.is_ordered = True
                i.save()
            
            
     
        return render(request, "main/shoppingcart.html", {
                    "Item_id": [],
                    "total": 0
                })

        

    else:
        return render(request, "main/shoppingcart.html", {
                    "Item_id": [],
                    "total": 0
                })



def index(request):
    total = 0

    if not request.session.session_key:
        request.session.save()

    order_qs = Order.objects.filter(OrderNumber=request.session.session_key+"1", is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]

    else:
        order = Order.objects.create(OrderNumber=request.session.session_key+"1")

    if request.method=="POST":
        Item_id = request.POST['product']
        item = Item.objects.get(id=Item_id)
        #order_item = Item.objects.get(id=Item_id)
        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            OrderNumber = request.session.session_key+"1",
            is_ordered= False
        )
        order_qs = Order.objects.filter(OrderNumber=request.session.session_key+"1", is_ordered=False)
        
        if order_qs.exists():
            order = order_qs[0]
            
            #check if orderitem is in order
            if order.products.filter(item__id=item.id).exists():
                order_item.quantity += 1
                order_item.save()
            else:
                order.products.add(order_item)
                order.save()

        else:
            order = Order.objects.create(OrderNumber=request.session.session_key+"1")
            order.products.add(order_item__id)
            order.save()

        for i in order.products.all():
            total += (i.item.price)*(i.quantity)

        order_item.subtotal = order_item.item.price*order_item.quantity
        order_item.save()

        return render(request, "main/shoppingcart.html", {
            "Item_id": order.products.all(),
            "total": total
        })

    else:

        order_qs = Order.objects.filter(OrderNumber=request.session.session_key+"1", is_ordered=False)


        if order_qs.exists():
            order = order_qs[0]

            total = 0

            for i in order.products.all():
                total += (i.item.price)*(i.quantity)

            return render(request, "main/shoppingcart.html", {
                    "Item_id": order.products.all(),
                    "total": total
                })
        else:
            return render(request, "main/shoppingcart.html", {
                    "Item_id": [],
                    "total": total
                })

    

nebs/main/templates/main/booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <title>Booking Page</title>
    <link rel="icon" href="{% static '/imgs/logo-png.png' %}">
</head>
<body>
    <div class="top-bar">
        <a href="{% url 'index' %}">
        <img src="{% static '/imgs/logo-png.png' %}" class="logo">
        </a>
        <nav class="navbar">
            <ul class="navbar-nav">
                <li class="nav-link "><a href="{% url 'display' cat='Bread'%}" >TARTES</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Cake'%}" >GATEAUX</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Pastry'%}">VIENNOISERIE</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Cookies'%}" >DÉJEUNER</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Moroccan'%}">MAROCAIN</a></li>
                <li class=" nav-link-icons">
                    <li class="nav-link"><a href="#" target="">
                        <div class="search-box">
                            <form action="/search" method="get">
                                <input class="search-txt" type="search" name="query" id = "query" placeholder="Recherche">
                                <button type = "submit" class="search-btn"><i class="fas fa-search search-box-icon"></i></button>
                            </form>
                        </div>
                    </a></li>
                    <li class="nav-link"><a href="{% url 'shoppingcart:index' %}" target="_blank"><i class="fas fa-shopping-cart"></i></a></li>
                </li>
            </ul>
        </nav>
      </div>

    
    <!--Grid Code Goes Here-->
    <main id = "container-booking"></main>
    <button class="send-booking-request">Envoyer la demande</button>

    <!--Popup Form Starts Here-->
    <div class="container">
        <form id="contact" action="" method="post">
          {% csrf_token %}
          <i class="fas fa-times close-container"></i>
          <h3>Demande de réservation: </h3>
          <h4>Contactez-nous aujourd'hui et recevez une réponse dans 24h!</h4>
          <fieldset>
            <input class="txt" placeholder="Nom et Prénom" type="text" tabindex="1" name = "name" required autofocus>
          </fieldset>
          <fieldset>
            <input class="txt" placeholder="Email" type="email" name = "email"  tabindex="2" required>
          </fieldset>
          <fieldset>
            <input class="txt" placeholder="Numéro de téléphone" type="tel" tabindex="3" name = "phone" pattern="[0-9]{10}" required>
            <small>Format: 0634567890</small>
          </fieldset>
          <fieldset>
            <div class="request-booking">
                <select required class="booking-time-dropdown" tabindex="4" name = "time" >
                    <option disabled selected hidden value="">Choisissez l'heure:</option>
                    <option value="6AM">6:00AM</option>
                    <option value="7AM">7:00AM</option>
                    <option value="8AM">8:00AM</option>
                    <option value="9AM">9:00AM</option>
                    <option value="10AM">10:00AM</option>
                    <option value="11AM">11:00AM</option>
                    <option value="12AM">12:00AM</option>
                    <option value="1PM">1:00PM</option>
                    <option value="2PM">2:00PM</option>
                    <option value="3PM">3:00PM</option>
                    <option value="4PM">4:00PM</option>
                    <option value="5PM">5:00PM</option>
                    <option value="6PM">6:00PM</option>
                    <option value="7PM">7:00PM</option>
                    <option value="8PM">8:00PM</option>
                    <option value="9PM">9:00PM</option>
                    <option value="10PM">10:00PM</option>
                    <option value="11PM">11:00PM</option>
                </select>
            </div>
          </fieldset>
          <fieldset>
            <div class="request-booking">
                <select required class="booking-day-dropdown" tabindex="5" name = "day" >
                    <option disabled selected hidden value="">Choisissez le jour:</option>
                    <option value="Lundi">Lundi</option>
                    <option value="Mardi">Mardi</option>
                    <option value="Mercredi">Mercredi</option>
                    <option value="Jeudi">Jeudi</option>
                    <option value="Vendredi">Vendredi</option>
                    <option value="Samedi">Samedi</option>
                    <option value="Dimanche">Dimanche</option>
                </select>
            </div>
          </fieldset>
          <fieldset>
            <label for="description">Spécifiez la raison de votre réservation:</label>
            <textarea class="txt" placeholder="Votre message ici...." tabindex="6" name = "description"  required></textarea>
          </fieldset>
          <fieldset>
            <button name="submit" type="submit" id="booking-submit" data-submit="...Envoi">Envoyer la demande</button>
          </fieldset>
        </form>  
    </div>
    <!--Popup Form Ends Here-->
    {% for message in messages %}
    <script>alert("{{ message }}");</script>
    {% endfor %}
    
    <div class="info">
        <div class="info-item">
            <i class="far fa-2x fa-clock"></i>
            <h3>HEURES D'OPÉRATION </h2>
                <span>Lundi au Mercredi: 8:00am - 6:00pm</span>
                <span>Samedi et Dimanche: 8:00am - 1:00pm</span>
            </div>
            <div class="info-item">
                <i class="fas fa-2x fa-map-marked-alt"></i>
                <h3>NOTRE MAGASIN</h2>
                <span>1234 First Avenue</span>
                <span>New Haven, CT 06509</span>
            </div>
            <div class="info-item">
                <i class="fas fa-2x fa-mobile-alt"></i>
                <h3>CONTACTEZ-NOUS</h2>
                <span>Numéro de téléphone #: 203-123-6789</span>
                <span>Email: contact@backery.com</span>
        </div>
    </div>
    <footer>© Nebs Bakery 2020</footer>
    <script src="{% static 'booking.js' %}"></script>
    <script> 
        window.onload = function(){
            let data = JSON.parse("{{data|escapejs}}"); 
            console.log(data);
            let len = data.length
            for(i = 0; i < len; i++){
                str = "."+data[i].fields.day +"-"+ data[i].fields.time;
                console.log(str);
                timeSlot = document.querySelector(str);
                timeSlot.style.backgroundColor = "red";
            }
        }
    </script>
</body>
</html>

nebs/main/templates/main/display.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Open+Sans:wght@300&display=swap" rel="stylesheet">    
    <title>{{ Cat }}</title>
    <link rel="icon" href="{% static '/imgs/logo-png.png' %}">
</head>
<body>
    <div class="top-bar">
        <a href="{% url 'index' %}">
            <img src="{% static '/imgs/logo-png.png' %}" class="logo">
        </a>
        <nav class="navbar">
            <ul class="navbar-nav">
                <li class="nav-link "><a href="{% url 'display' cat='Bread'%}" >TARTES</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Cake'%}" >GATEAUX</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Pastry'%}">VIENNOISERIE</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Cookies'%}" >DÉJEUNER</a></li>
                <li class="nav-link"><a href="{% url 'display' cat='Moroccan'%}">MAROCAIN</a></li>
                <li class=" nav-link-icons">
                    <li class="nav-link"><a href="#" target="">
                        <div class="search-box">
                            <form action="/search" method="get">
                                <input class="search-txt" type="search" name="query" id = "query" placeholder="Recherche">
                                <button type = "submit" class="search-btn"><i class="fas fa-search search-box-icon"></i></button>
                            </form>
                        </div>
                    </a></li>
                    <li class="nav-link"><a href="{% url 'shoppingcart:index' %}" target="_blank"><i class="fas fa-shopping-cart"></i></a></li>
                </li>
            </ul>
        </nav>
    </div>

    <div class="display-items-container">
        <div class="select">
            <select class="sort-dropdown">
                <option selected="selected" disabled>Sort by:</option>
                <option value="name">Product Name</option>
                <option value="price-ascending">Ascending Price</option>
                <option value="price-descending">Descending Price</option>
            </select>
        </div>
  
        <div class="display-items-grid">
            {% for item in Items %}
            <ul class="item-zone">
                <li class="item-image"><img src="{% static item.picture|cut:'main/static' %}" alt="" srcset=""></li>
                <li class="item-name">{{ item.name }}</li>
                <li class="item-price">{{ item.price }}</li>
                <li class="item-description">{{ item.description }}</li>
                <form method="POST" action="{% url 'shoppingcart:index' %}">
                   <!-- <input type="text" value ='{{ item.id }}'>-->
                   {% csrf_token %}
                   <input type="hidden" name="product" value='{{ item.id }}'>
                   <!--{{ form }}-->
                <input type ="submit" class="btn btn-display" value="Ajouter au panier"></input>
                </form>
            </ul>
            {% endfor %}
        </div>
    </div>
    
    
    <div class="info">
        <div class="info-item">
            <i class="far fa-2x fa-clock"></i>
            <h3>HEURES D'OPÉRATION </h2>
                <span>Lundi au Mercredi: 8:00am - 6:00pm</span>
                <span>Samedi et Dimanche: 8:00am - 1:00pm</span>
            </div>
            <div class="info-item">
                <i class="fas fa-2x fa-map-marked-alt"></i>
                <h3>NOTRE MAGASIN</h2>
                <span>1234 First Avenue</span>
                <span>New Haven, CT 06509</span>
            </div>
            <div class="info-item">
                <i class="fas fa-2x fa-mobile-alt"></i>
                <h3>CONTACTEZ-NOUS</h2>
                <span>Numéro de téléphone #: 203-123-6789</span>
                <span>Email: contact@backery.com</span>
        </div>
    </div>
    <footer>© Nebs Bakery 2020</footer>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

nebs/main/templates/main/shoppingcart.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous"/>
  <link rel="icon" href="{% static '/imgs/logo-png.png' %}">
  
  <link rel="stylesheet" href="/static/shopping.css? {% now "U" %}"/> 
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
  <title>Panier</title>
  
 
  <script src="{% static shop.js %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<div class="top-bar">
  <a href="{% url 'index' %}">
  <img src="{% static '/imgs/logo-png.png' %}" class="logo">
  </a>
  <nav class="navbar">
      <ul class="navbar-nav">
        <li class="nav-link "><a href="{% url 'display' cat='Bread'%}" >TARTES</a></li>
        <li class="nav-link"><a href="{% url 'display' cat='Cake'%}" >GATEAUX</a></li>
        <li class="nav-link"><a href="{% url 'display' cat='Pastry'%}">VIENNOISERIE</a></li>
        <li class="nav-link"><a href="{% url 'display' cat='Cookies'%}" >DÉJEUNER</a></li>
        <li class="nav-link"><a href="{% url 'display' cat='Moroccan'%}">MAROCAIN</a></li>
          <li class=" nav-link-icons">
              <li class="nav-link"><a href="#" target="">
                  <div class="search-box">
                      <form action="/search" method="get">
                          <input class="search-txt" type="search" name="query" id = "query" placeholder="Recherche">
                          <button type = "submit" class="search-btn"><i class="fas fa-search search-box-icon"></i></button>
                      </form>
                  </div>
              </a></li>
              <li class="nav-link"><a href="{% url 'shoppingcart:index' %}" target="_blank"><i class="fas fa-shopping-cart"></i></a></li>
          </li>
      </ul>
  </nav>
</div>

<body>
  <main>
      
    <div class = "shopping-title">
        MON PANIER
    </div>

    <div class="basket">
      <div class="basket-labels">
        <ul>
          <li class="item item-heading">Produit</li>
          <li class="price">Prix</li>
          <li class="quantity">Quantité</li>
          <li class="subtotal">Sous-total</li>
        </ul>
      </div>
      {% for Id in Item_id %}
      <div class="basket-product">
        <div class="item">
          <div class="product-image">
            <img src="{% static Id.item.picture|cut:'main/static' %}" alt="Placholder Image 2" width="120" height="120" class="product-frame" srcset="">
          </div>
          <div class="product-details">
            <h1><strong><span class="item-quantity">{{ Id.quantity }}</span> x </strong>  {{ Id.item.name }} </h1>
            <p><strong>{{ Id.item.description }}</strong></p>
            <p>{{ Id.item.category }}</p>
          </div>
        </div>
        <div class="price">{{ Id.item.price }}</div>
        <div class="quantity">
          <button class="buttonsub">
            -
          </button>
          <input type="number" id="MEH" value="{{ Id.quantity }}" min="1" class="quantity-field">
          <button class="buttonadd">
            +
          </button>
        </div>
        <div class="subtotal">{{ Id.subtotal }}</div>
        <div class="remove">
          <button>Supprimer</button>
        </div>
      </div>
      {% empty %}
      <li class= "none"> Oops, le panier est vide. </li>
      {% endfor %}
    </div>
    <aside>
      <div class="summary">
        <div class="summary-total-items"><span class="total-items"></span> Produits dans mon panier </div>
        <div class="summary-subtotal">
          <div class="subtotal-title">Sous-total</div>
          <div class="subtotal-value final-value" id="basket-subtotal">{{ total }}</div>
        </div>
        
        <form method="POST" action="{% url 'shoppingcart:confirm' %}">
          <div class="summary-delivery">
            <select id="test" name="form_select" onchange="showDiv('hidden_div', this)" class="summary-delivery-selection">
            <!--<select id="myselect" name="delivery-collection">-->
                <option value="0" selected="selected">Selectionner retrait en magasin ou livraison</option>
               <option value="2">Retrait en magasin</option>
               <option value="1">Frais de livraison</option>
            </select>
          </div>
        <div class="client-info">
              {% csrf_token %}
                <label for="fname">Prénom:</label>
                <input class="txt" type="text" id="fname" name="fname" required><br><br>
                <label for="lname">Nom:</label>
                <input class="txt" type="text" id="lname" name="lname" required><br><br>
                <label for="number">Numéro de téléphone:</label>
                <input class="txt" type="text" id="number" name="number" required><br><br>
                <div id="hidden_div" style="display:none;">
                <label for="address" >Addresse: </label>
                <input placeholder="Addresse" class="txt" id="address" name="address" value=" " type="text" required><br><br>
                <div class="summary-subtotal">
                    <div class="subtotal-title">Delivery charge</div>
                    <div class="subtotal-value final-value"> 15</div>
                  </div>
                </div>
                <div class="summary-total">
                    <div class="total-title">Total</div>
                    <div class="total-value final-value" id="basket-total">{{ total }}</div>
                    <input type="hidden" value='{{ total }}' name="ttl">
                  </div>
                <div class="summary-checkout">
                    <input type="submit" value="Confirmer la commande" class="checkout-cta">
            </div>
            </form>
        </div>        
      </div>
    </aside>
  </main>
  
  <script src="{% static 'shop.js' %}"></script>
</body>

<div class="info">
    <div class="info-item">
        <i class="far fa-2x fa-clock"></i>
        <h3>HEURES D'OPÉRATION </h2>
          <span>Lundi au Mercredi: 8:00am - 6:00pm</span>
          <span>Samedi et Dimanche: 8:00am - 1:00pm</span>
      </div>
      <div class="info-item">
          <i class="fas fa-2x fa-map-marked-alt"></i>
          <h3>NOTRE MAGASIN</h2>
          <span>1234 First Avenue</span>
          <span>New Haven, CT 06509</span>
      </div>
      <div class="info-item">
          <i class="fas fa-2x fa-mobile-alt"></i>
          <h3>CONTACTEZ-NOUS</h2>
          <span>Numéro de téléphone #: 203-123-6789</span>
          <span>Email: contact@backery.com</span>
    </div>
</div>

<footer>© Nebs Bakery 2020</footer>

</html>